### ISSUE TITLE
after deploy LimSimLight , meet this problem

### ISSUE THREAD

**Issue by baibingren** [PJLab-ADG/LimSim#34]
---------- 2024-10-11 22:55:48 model initializes ... ----------
The opendrive file has been pasred.
The road waypoint has been got.
The road network topology has been built.
The road boundary has been got.
The network information have been loaded.
Traceback (most recent call last):
  File "/home/mellon/anaconda3/envs/limsim312/lib/python3.12/site-packages/peewee.py", line 3322, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: no such table: vehicledb

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mellon/mellon/repo/LimSim/ModelExample.py", line 96, in <module>
    replay_model(net_file)
  File "/home/mellon/mellon/repo/LimSim/ModelExample.py", line 59, in replay_model
    model.replayMoveStep()
  File "/home/mellon/mellon/repo/LimSim/simModel/model.py", line 217, in replayMoveStep
    self.run_time = self.db.getRunTime()
                    ^^^^^^^^^^^^^^^^^^^^
  File "/home/mellon/mellon/repo/LimSim/simModel/common/dataBase.py", line 93, in getRunTime
    return VehicleDB.select(pw.fn.Max(VehicleDB.timeStep)).scalar()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mellon/anaconda3/envs/limsim312/lib/python3.12/site-packages/peewee.py", line 2036, in inner
    return method(self, database, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mellon/anaconda3/envs/limsim312/lib/python3.12/site-packages/peewee.py", line 2301, in scalar
    row = self.tuples().peek(database)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mellon/anaconda3/envs/limsim312/lib/python3.12/site-packages/peewee.py", line 2036, in inner
    return method(self, database, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mellon/anaconda3/envs/limsim312/lib/python3.12/site-packages/peewee.py", line 2286, in peek
    rows = self.execute(database)[:n]
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mellon/anaconda3/envs/limsim312/lib/python3.12/site-packages/peewee.py", line 2036, in inner
    return method(self, database, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mellon/anaconda3/envs/limsim312/lib/python3.12/site-packages/peewee.py", line 2107, in execute
    return self._execute(database)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mellon/anaconda3/envs/limsim312/lib/python3.12/site-packages/peewee.py", line 2280, in _execute
    cursor = database.execute(self)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mellon/anaconda3/envs/limsim312/lib/python3.12/site-packages/peewee.py", line 3330, in execute
    return self.execute_sql(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mellon/anaconda3/envs/limsim312/lib/python3.12/site-packages/peewee.py", line 3320, in execute_sql
    with __exception_wrapper__:
         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mellon/anaconda3/envs/limsim312/lib/python3.12/site-packages/peewee.py", line 3088, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/home/mellon/anaconda3/envs/limsim312/lib/python3.12/site-packages/peewee.py", line 196, in reraise
    raise value.with_traceback(tb)
  File "/home/mellon/anaconda3/envs/limsim312/lib/python3.12/site-packages/peewee.py", line 3322, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: no such table: vehicledb

**Comment by pinlong-cai** [comment]
Hello! It would help if you ran the real-time simulation by "python ModelExample.py" to create the database file (*.db) first, and then you can run the simulation replay by "python ModelExample.py replay".

We have also updated this note to the readme to help subsequent developers. We appreciate your help!
